name = "nil"
description = "nil isn't lisp"
version = "0.1.0-dev"

authors = ["Daniel Smith"]
maintainers = ["Daniel Smith <example@example.com>"]
licenses = "GPL-3.0-or-later"
website = ""
tags = []

executables = ["nil"]

[configuration]
disabled = true
output_dir = "./alire-config"
generate_ada = false
generate_gpr = false
generate_c = false
auto_gpr_with = false

[[depends-on]]
gnat = "^15.1.2"

[[depends-on]]
gnatcov = "^22.0.1"

[[depends-on]]
gnatprove = "^15.1.0"
